use super::*;

pub(super) fn append_status_preemptive_risk_lines(
    lines: &mut Vec<String>,
    report: &MeshRuntimeStatusReport,
) {
    lines.push(format!(
        "status_preemptive_shadow_pri={:.2}",
        report.preemptive_shadow_pri
    ));
    lines.push(format!(
        "status_preemptive_shadow_instant_risk={:.4}",
        report.preemptive_shadow_instant_risk
    ));
    lines.push(format!(
        "status_preemptive_shadow_trend_risk={:.4}",
        report.preemptive_shadow_trend_risk
    ));
    lines.push(format!(
        "status_preemptive_shadow_stage={}",
        report.preemptive_shadow_stage
    ));
    lines.push(format!(
        "status_preemptive_shadow_trigger={}",
        report.preemptive_shadow_trigger
    ));
    lines.push(format!(
        "status_preemptive_shadow_risk_summary={}",
        report.preemptive_shadow_risk_summary
    ));
}

pub(super) fn append_status_preemptive_switch_lines(
    lines: &mut Vec<String>,
    report: &MeshRuntimeStatusReport,
) {
    lines.push(format!(
        "status_preemptive_shadow_switch_prepare={}",
        report.preemptive_shadow_switch_prepare
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_recommend={}",
        report.preemptive_shadow_switch_recommend
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_reason={}",
        report.preemptive_shadow_switch_reason
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_guard={}",
        report.preemptive_shadow_switch_guard
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_guard_source={}",
        report.preemptive_shadow_switch_guard_source
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_guard_summary={}",
        report.preemptive_shadow_switch_guard_summary
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_block_reason_chain=reason={};guard={};source={}",
        report.preemptive_shadow_switch_reason,
        report.preemptive_shadow_switch_guard,
        report.preemptive_shadow_switch_guard_source
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_confidence={:.4}",
        report.preemptive_shadow_switch_confidence
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_candidate_confidence={:.4}",
        report.preemptive_shadow_switch_candidate_confidence
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_confidence_gate_min={:.4}",
        report.preemptive_shadow_switch_confidence_gate_min
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_confidence_gate_passed={}",
        report.preemptive_shadow_switch_confidence_gate_passed
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_target={}",
        report.preemptive_shadow_switch_target
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_candidate_sample_age_ticks={}",
        report.preemptive_shadow_switch_candidate_sample_age_ticks
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_confidence_summary=conf={:.4};min={:.4};passed={};sample_age_ticks={}",
        report.preemptive_shadow_switch_candidate_confidence,
        report.preemptive_shadow_switch_confidence_gate_min,
        report.preemptive_shadow_switch_confidence_gate_passed,
        report.preemptive_shadow_switch_candidate_sample_age_ticks
    ));
    lines.push(format!(
        "status_preemptive_shadow_candidate_readiness_summary=eligible={};switch_valid={};health_blocked={};confidence_gate_passed={};sample_age_ticks={}",
        report.preemptive_shadow_eligible_candidates,
        report.preemptive_shadow_switch_valid,
        report.preemptive_shadow_health_blocked_count,
        report.preemptive_shadow_switch_confidence_gate_passed,
        report.preemptive_shadow_switch_candidate_sample_age_ticks
    ));
    lines.push(format!(
        "status_preemptive_shadow_switch_mode={}",
        report.preemptive_shadow_switch_mode
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_status={}",
        report.preemptive_shadow_hints_status
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_source={}",
        report.preemptive_shadow_hints_source
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_reason={}",
        report.preemptive_shadow_hints_reason
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_present={}",
        report.preemptive_shadow_hints_present
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_multipath_mode={}",
        report.preemptive_shadow_hints_multipath_mode
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_continuity_policy={}",
        report.preemptive_shadow_hints_continuity_policy
    ));
    lines.push(format!(
        "status_preemptive_shadow_hints_summary={}",
        report.preemptive_shadow_hints_summary
    ));
    lines.push(format!(
        "status_preemptive_shadow_action={}",
        report.preemptive_shadow_action
    ));
    lines.push(format!(
        "status_preemptive_shadow_action_reason={}",
        report.preemptive_shadow_action_reason
    ));
    lines.push(format!(
        "status_preemptive_shadow_action_state={}",
        report.preemptive_shadow_action_state
    ));
    lines.push(format!(
        "status_preemptive_shadow_action_priority={}",
        report.preemptive_shadow_action_priority
    ));
}
