pub(crate) struct SourceList {
    pub(crate) id: &'static str,
    pub(crate) start: i64,
    pub(crate) end: i64,
    pub(crate) items: &'static [&'static str],
}

pub(crate) struct StageSourceRange {
    pub(crate) stage: &'static str,
    pub(crate) start: i64,
    pub(crate) end: i64,
    pub(crate) non_empty_lines: i64,
    pub(crate) marker_lines: i64,
}

pub(crate) const SOURCE_SHA256: &str =
    "c03a66bf5359c83696233b3abc20681eada471d30ba3f9191a2e20abd36f901a";
pub(crate) const SOURCE_LINE_COUNT: i64 = 5405;
pub(crate) const SOURCE_NEWLINE_COUNT: i64 = 5404;
pub(crate) const SOURCE_NON_EMPTY_LINE_COUNT: i64 = 2703;
pub(crate) const SOURCE_BULLET_LINE_COUNT: i64 = 1229;
pub(crate) const SOURCE_NUMBERED_LINE_COUNT: i64 = 38;
pub(crate) const SOURCE_UPPER_HEADING_LINE_COUNT: i64 = 227;
pub(crate) const SOURCE_STRUCTURAL_HEADING_LINE_COUNT: i64 = 168;
pub(crate) const SOURCE_REQUIRED_MARKER_LINE_COUNT: i64 = 1494;

const COUNCIL_INTERDISCIPLINARY_DISCIPLINES: [&str; 37] = [
    "• mathematics;",
    "• discrete mathematics;",
    "• linear algebra;",
    "• graph theory;",
    "• probability theory;",
    "• statistics;",
    "• operations research;",
    "• optimisation theory;",
    "• game theory;",
    "• information theory;",
    "• control theory;",
    "• complex systems theory;",
    "• queueing theory;",
    "• automata theory;",
    "• category theory;",
    "• logic;",
    "• cryptography;",
    "• physics;",
    "• chemistry;",
    "• biology;",
    "• genetics;",
    "• neuroscience;",
    "• evolutionary biology;",
    "• ecology;",
    "• cognitive sciences;",
    "• psychology;",
    "• economics;",
    "• sociology;",
    "• organisation theory;",
    "• distributed systems;",
    "• network science;",
    "• robotics;",
    "• aerospace engineering;",
    "• mechanics;",
    "• systems engineering;",
    "• reliability theory;",
    "• any other disciplines",
];

const COUNCIL_FUNDAMENTAL_KNOWLEDGE_ITEMS: [&str; 23] = [
    "• theories;",
    "• models;",
    "• mathematical frameworks;",
    "• axioms;",
    "• theorems;",
    "• laws;",
    "• invariants;",
    "• patterns;",
    "• heuristics;",
    "• architectural principles;",
    "• strategies;",
    "• mechanisms;",
    "• algorithms;",
    "• ways of self‑organisation;",
    "• ways of collective behaviour;",
    "• ways of decision‑making;",
    "• ways of learning;",
    "• ways of recovery after failures;",
    "• ways of ensuring stability;",
    "• ways of balancing;",
    "• ways of scaling;",
    "• ways of localising errors;",
    "• ways of minimising complexity.",
];

const STAGE_RESEARCH_DISCIPLINES: [&str; 33] = [
    "• mathematics;",
    "• discrete mathematics;",
    "• linear algebra;",
    "• graph theory;",
    "• probability theory;",
    "• statistics;",
    "• operations research;",
    "• optimisation theory;",
    "• game theory;",
    "• information theory;",
    "• control theory;",
    "• automata theory;",
    "• category theory;",
    "• cryptography;",
    "• physics;",
    "• chemistry;",
    "• biology;",
    "• genetics;",
    "• neuroscience;",
    "• ecology;",
    "• evolutionary biology;",
    "• cognitive sciences;",
    "• psychology;",
    "• economics;",
    "• sociology;",
    "• network science;",
    "• distributed systems;",
    "• robotics;",
    "• aerospace engineering;",
    "• mechanics;",
    "• systems engineering;",
    "• reliability theory;",
    "• any other disciplines",
];

const STAGE_RESEARCH_FUNDAMENTAL_ITEMS: [&str; 29] = [
    "• theories;",
    "• mathematical models;",
    "• axioms;",
    "• theorems;",
    "• laws;",
    "• fundamental constraints;",
    "• invariants;",
    "• patterns;",
    "• cause‑and‑effect relationships;",
    "• heuristics;",
    "• behaviour models;",
    "• principles;",
    "• architectural patterns;",
    "• strategies;",
    "• mechanisms;",
    "• algorithms;",
    "• optimisation methods;",
    "• self‑organisation methods;",
    "• adaptation methods;",
    "• decision‑making methods;",
    "• collective behaviour methods;",
    "• learning methods;",
    "• search methods;",
    "• balancing methods;",
    "• recovery after failure methods;",
    "• error localisation methods;",
    "• stability assurance methods;",
    "• scaling methods;",
    "• complexity reduction methods.",
];

const KNOWLEDGE_TRANSFER_CHECKS: [&str; 8] = [
    "• what fundamental properties make it successful;",
    "• what invariants underlie it;",
    "• what constraints are mandatory;",
    "• which parts of the principle can be transferred;",
    "• which parts cannot be transferred;",
    "• what adaptations are necessary;",
    "• what advantages the transfer will bring;",
    "• what new risks the transfer creates.",
];

const ANALOGICAL_THINKING_QUESTIONS: [&str; 19] = [
    "• How would a mathematician solve this problem?",
    "• How would a physicist solve it?",
    "• How would a chemist solve it?",
    "• How would a biologist solve it?",
    "• How would evolution solve it?",
    "• How would nature solve it?",
    "• How would an information theorist solve it?",
    "• How would a cryptographer solve it?",
    "• How would a specialist in distributed systems solve it?",
    "• How would an aerospace engineer solve it?",
    "• How would a spacecraft engineer solve it?",
    "• How would a systems engineering specialist solve it?",
    "• How would a fault‑tolerance specialist solve it?",
    "• How would an operations researcher solve it?",
    "• How would an economist solve it?",
    "• How would a specialist in collective behaviour solve it?",
    "• What analogous problems have already been solved in other fields of science?",
    "• What fundamental principles made those solutions successful?",
    "• Which of these principles can be safely transferred to the current problem?",
];

const FOUND_IDEA_EVALUATION_CRITERIA: [&str; 12] = [
    "• evidence base;",
    "• maturity;",
    "• fundamentality;",
    "• universality;",
    "• scalability;",
    "• stability;",
    "• implementation complexity;",
    "• integration feasibility;",
    "• compatibility with existing architecture;",
    "• impact on invariants;",
    "• potential risks;",
    "• potential engineering gain.",
];

pub(crate) const INTERDISCIPLINARY_SOURCE_LISTS: [SourceList; 7] = [
    SourceList {
        id: "council_interdisciplinary_disciplines",
        start: 797,
        end: 873,
        items: &COUNCIL_INTERDISCIPLINARY_DISCIPLINES,
    },
    SourceList {
        id: "council_fundamental_knowledge_items",
        start: 883,
        end: 927,
        items: &COUNCIL_FUNDAMENTAL_KNOWLEDGE_ITEMS,
    },
    SourceList {
        id: "stage_research_disciplines",
        start: 3161,
        end: 3229,
        items: &STAGE_RESEARCH_DISCIPLINES,
    },
    SourceList {
        id: "stage_research_fundamental_items",
        start: 3237,
        end: 3295,
        items: &STAGE_RESEARCH_FUNDAMENTAL_ITEMS,
    },
    SourceList {
        id: "knowledge_transfer_checks",
        start: 3307,
        end: 3323,
        items: &KNOWLEDGE_TRANSFER_CHECKS,
    },
    SourceList {
        id: "analogical_thinking_questions",
        start: 3415,
        end: 3451,
        items: &ANALOGICAL_THINKING_QUESTIONS,
    },
    SourceList {
        id: "found_idea_evaluation_criteria",
        start: 3457,
        end: 3481,
        items: &FOUND_IDEA_EVALUATION_CRITERIA,
    },
];

pub(crate) const STAGE_SOURCE_RANGES: [StageSourceRange; 8] = [
    StageSourceRange {
        stage: "analyze",
        start: 1,
        end: 2250,
        non_empty_lines: 1125,
        marker_lines: 599,
    },
    StageSourceRange {
        stage: "impact_analysis",
        start: 2251,
        end: 2646,
        non_empty_lines: 198,
        marker_lines: 114,
    },
    StageSourceRange {
        stage: "research_planning",
        start: 2647,
        end: 3028,
        non_empty_lines: 191,
        marker_lines: 113,
    },
    StageSourceRange {
        stage: "research",
        start: 3029,
        end: 3652,
        non_empty_lines: 312,
        marker_lines: 194,
    },
    StageSourceRange {
        stage: "architecture_synthesis",
        start: 3653,
        end: 4138,
        non_empty_lines: 243,
        marker_lines: 113,
    },
    StageSourceRange {
        stage: "implementation",
        start: 4139,
        end: 4564,
        non_empty_lines: 213,
        marker_lines: 115,
    },
    StageSourceRange {
        stage: "validation",
        start: 4565,
        end: 4980,
        non_empty_lines: 208,
        marker_lines: 115,
    },
    StageSourceRange {
        stage: "postmortem",
        start: 4981,
        end: 5405,
        non_empty_lines: 213,
        marker_lines: 131,
    },
];
