#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
POLICY_FILE="$ROOT_DIR/configs/policy.runtime.conf"
DOMAINS_FILE="$ROOT_DIR/configs/adaptive_domains.txt"
LOG_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/chimera"
LOG_FILE="$LOG_DIR/autofix.log"
CURL_MAX_TIME="${CHIMERA_AUTOFIX_CURL_MAX_TIME:-4}"
mkdir -p "$LOG_DIR"

timestamp="$(date '+%F %T')"
echo "--- $timestamp autofix start ---" >>"$LOG_FILE"

if [[ ! -f "$DOMAINS_FILE" ]]; then
  cat >"$DOMAINS_FILE" <<'EOF'
youtube.com
googlevideo.com
ytimg.com
gstatic.com
EOF
fi

tmp_policy="$(mktemp)"
{
  echo "# AUTO-GENERATED by chimera-autofix.sh"
  echo "# Do not edit manually; update configs/adaptive_domains.txt instead."
} >"$tmp_policy"

idx=0
failed=0
while IFS= read -r raw_domain; do
  domain="$(echo "$raw_domain" | tr -d '[:space:]')"
  [[ -z "$domain" ]] && continue
  [[ "$domain" == \#* ]] && continue

  idx=$((idx + 1))
  code="$(curl -sS -L --max-time "$CURL_MAX_TIME" -o /dev/null -w '%{http_code}' "https://$domain" 2>/dev/null || true)"

  if [[ "$code" == "200" || "$code" == "301" || "$code" == "302" || "$code" == "303" ]]; then
    echo "probe[$idx] $domain => direct (http=$code)" >>"$LOG_FILE"
    echo "${domain//./-}-direct = suffix:$domain => direct" >>"$tmp_policy"
  else
    failed=$((failed + 1))
    echo "probe[$idx] $domain => gateway (http=$code)" >>"$LOG_FILE"
    echo "${domain//./-}-gateway = suffix:$domain => gateway" >>"$tmp_policy"
  fi
done <"$DOMAINS_FILE"

if [[ "$failed" -gt 0 ]]; then
  echo "default-gateway = default => gateway" >>"$tmp_policy"
  echo "autofix decision: default route switched to gateway (failed_domains=$failed)" >>"$LOG_FILE"
else
  echo "default-direct = default => direct" >>"$tmp_policy"
  echo "autofix decision: default route remains direct (failed_domains=0)" >>"$LOG_FILE"
fi
mv "$tmp_policy" "$POLICY_FILE"

echo "runtime policy path: $POLICY_FILE" >>"$LOG_FILE"
