use chimera_mesh::{MeshJoinMode, MeshPathPlan};

use super::options::MeshRouteExplainOptions;

pub(crate) struct MeshRouteExplainRender<'a> {
    pub(crate) contract_version: &'a str,
    pub(crate) options: &'a MeshRouteExplainOptions,
    pub(crate) initial: &'a MeshPathPlan,
    pub(crate) failover_selected: &'a str,
    pub(crate) cooldown_selected: &'a str,
}

pub(crate) struct MeshRouteExplainFields {
    pub(crate) contract_version: String,
    pub(crate) namespace: String,
    pub(crate) node_name: String,
    pub(crate) join_mode: MeshJoinMode,
    pub(crate) initial_selected: String,
    pub(crate) failover_selected: String,
    pub(crate) cooldown_selected: String,
    pub(crate) table_runtime_consistency_gate: String,
    pub(crate) table_runtime_consistency_all_true: String,
    pub(crate) table_runtime_consistency_summary: String,
    pub(crate) plan_setup_discovery_table_compact: String,
    pub(crate) plan_setup_discovery_table_compact_consistency: String,
    pub(crate) plan_setup_discovery_table_compact_consistency_match: String,
    pub(crate) plan_setup_discovery_table_compact_consistency_match_source: String,
    pub(crate) status_plan_setup_compact_consistency_match_source: String,
    pub(crate) status_setup_compact_consistency_match_source: String,
    pub(crate) status_shadow_setup_match_source_from_compact: String,
    pub(crate) status_shadow_plan_setup_match_source_from_compact: String,
    pub(crate) dps_payload_plan_setup_compact_consistency: String,
    pub(crate) setup_compact_consistency_match: String,
    pub(crate) setup_compact_consistency_match_source: String,
    pub(crate) dps_payload_plan_setup_compact_consistency_match: String,
    pub(crate) dps_payload_plan_setup_compact_consistency_match_source: String,
    pub(crate) dps_payload_setup_compact_consistency_match: String,
    pub(crate) dps_payload_setup_compact_consistency_match_source: String,
    pub(crate) dps_shadow_setup_match_source_from_compact: String,
    pub(crate) dps_shadow_plan_setup_match_source_from_compact: String,
    pub(crate) dps_payload_selection_pressure_summary: String,
    pub(crate) dps_payload_selection_pressure_level: String,
    pub(crate) dps_payload_selection_pressure_score: String,
    pub(crate) dps_payload_selection_pressure_dominant: String,
    pub(crate) dps_payload_selection_pressure_action_hint: String,
    pub(crate) dps_payload_selection_pressure_compact: String,
    pub(crate) dps_payload_selection_pressure_reason: String,
    pub(crate) selection_pressure_projection_consistency: String,
    pub(crate) selection_pressure_projection_gate: String,
    pub(crate) route_explain_health_gate: String,
    pub(crate) route_explain_health_summary: String,
    pub(crate) route_explain_operator_summary: String,
    pub(crate) route_explain_operator_signature: String,
    pub(crate) route_explain_operator_route_key: String,
    pub(crate) route_explain_operator_health: String,
    pub(crate) route_explain_operator_selected: String,
    pub(crate) route_explain_operator_pressure: String,
    pub(crate) route_explain_operator_action: String,
    pub(crate) route_explain_operator_reason: String,
    pub(crate) route_explain_contract_integrity: String,
    pub(crate) consistency_source_matrix: String,
    pub(crate) dps_payload_preemptive_shadow_compact: String,
    pub(crate) preemptive_degraded_path: String,
    pub(crate) preemptive_degraded_reason: String,
    pub(crate) preemptive_shadow_degraded_summary: String,
    pub(crate) preemptive_shadow_switch_candidate_confidence: String,
    pub(crate) preemptive_shadow_switch_confidence_gate_min: String,
    pub(crate) preemptive_shadow_switch_confidence_gate_passed: String,
    pub(crate) preemptive_shadow_switch_candidate_sample_age_ticks: String,
    pub(crate) preemptive_shadow_switch_confidence_summary: String,
    pub(crate) preemptive_shadow_switch_block_reason_chain: String,
    pub(crate) preemptive_shadow_candidate_readiness_summary: String,
    pub(crate) auto_recovery_attempts: String,
    pub(crate) auto_recovery_final_result: String,
    pub(crate) connect_retry_budget_exhausted: String,
    pub(crate) connect_recovery_needed: String,
    pub(crate) connect_recovery_strategy: String,
    pub(crate) connect_recovery_projection_consistency: String,
    pub(crate) connect_recovery_projection_key: String,
    pub(crate) route_explain_recovery_schema_version: String,
    pub(crate) route_explain_recovery_fields_checksum: String,
    pub(crate) selection_pressure_summary: String,
    pub(crate) selection_pressure_level: String,
    pub(crate) selection_pressure_score: String,
    pub(crate) selection_pressure_dominant: String,
    pub(crate) selection_pressure_action_hint: String,
    pub(crate) selection_pressure_compact: String,
    pub(crate) selection_pressure_reason: String,
    pub(crate) selected_peer_connect_retry_plan: String,
    pub(crate) selected_peer_connect_backoff_profile: String,
    pub(crate) explain: String,
}
