pub(crate) const SUCCESS_SELECTED_NODE: &str = "n1";
pub(crate) const SUCCESS_PRESSURE: &str = "saturated";
pub(crate) const SUCCESS_OPERATOR_ACTION: &str = "use_selected_path";
pub(crate) const SUCCESS_OPERATOR_REASON: &str = "none";

pub(crate) const ERROR_SELECTED_NONE: &str = "none";
pub(crate) const ERROR_PRESSURE_UNKNOWN: &str = "unknown";
pub(crate) const UNKNOWN_VALUE: &str = "unknown";
pub(crate) const BOOL_FALSE: &str = "false";
pub(crate) const BOOL_TRUE: &str = "true";
pub(crate) const INTEGRITY_ALL_TRUE: &str =
    "signature_match:true;route_key_match:true;health_gate_match:true";
pub(crate) const INTEGRITY_ROUTE_KEY_FALSE: &str =
    "signature_match:true;route_key_match:false;health_gate_match:true";

pub(crate) const SOURCE_DERIVED: &str = "derived";
pub(crate) const SOURCE_STATUS_REPORT: &str = "status_report";
pub(crate) const SOURCE_PLAN_SETUP_EXPLAIN: &str = "plan_setup_explain";
pub(crate) const SOURCE_SETUP_COMPUTED: &str = "computed_from_setup_compact";
pub(crate) const SOURCE_PLAN_SETUP_COMPACT: &str = "plan_setup_compact";

pub(crate) use super::route_explain_error_consts::{
    ACTION_ADJUST_POLICY_OR_PEERS as ERROR_ACTION_ADJUST_POLICY, ACTION_FIX_PEER_SPEC,
    ACTION_FIX_POLICY_PAYLOAD, ACTION_FIX_TABLE_POLICY, ACTION_INSPECT_DISCOVERY_INPUT,
    ACTION_INSPECT_ERROR, ACTION_INSPECT_FAILOVER_INPUT, ACTION_INSPECT_HEALTH_INPUTS,
    ACTION_INSPECT_RUNTIME_BOOTSTRAP, BACKOFF_AFTER_FIX, BACKOFF_IMMEDIATE, BACKOFF_SHORT,
    CATEGORY_HEALTH, CATEGORY_INPUT, CATEGORY_PLANNING, CATEGORY_POLICY, CATEGORY_RUNTIME,
    CATEGORY_UNKNOWN, RESOLUTION_ADJUST_TABLE_POLICY_BOUNDS as RESOLUTION_TABLE_POLICY_BOUNDS,
    RESOLUTION_CHECK_PEER_SPEC_FORMAT as RESOLUTION_CHECK_PEER_SPEC,
    RESOLUTION_FIX_POLICY_PAYLOAD_SYNTAX as RESOLUTION_POLICY_PAYLOAD_SYNTAX,
    RESOLUTION_INSPECT_DISCOVERY_RECORDS, RESOLUTION_INSPECT_ERROR_DETAILS,
    RESOLUTION_INSPECT_FAILOVER_EVENT, RESOLUTION_INSPECT_HEALTH_STATE,
    RESOLUTION_INSPECT_RUNTIME_NAMESPACE,
    RESOLUTION_RELAX_POLICY_OR_ADD_CANDIDATES as RESOLUTION_RELAX_POLICY, RETRIABLE_FALSE,
    RETRIABLE_TRUE, STAGE_DISCOVERY_MERGE, STAGE_FAILOVER_PLAN, STAGE_HEALTH_STATE_UPDATE,
    STAGE_OPTIONS_PARSE, STAGE_PEER_SPEC, STAGE_PEER_TABLE_POLICY,
    STAGE_PLAN_PATH as ERROR_STAGE_PLAN_PATH, STAGE_POLICY_PARSE, STAGE_RESELECTION_PLAN,
    STAGE_RUNTIME_BOOTSTRAP, STAGE_SIMULATION_INPUT,
};
